# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4049a981005683c4236497cf2b37580fe4976268d409049cf32e33fed2acd576a2619e439b2ff7f9f8bfa515f9375dea0c49bba57de8ca3258c311bb175901ea

test:
  secret_key_base: cb7384692a329744f7e7329b59df68949c6fc2eb4b66dffd25be4da10aca5e4d1d603962b838f92701ad3158c86899fbc9615c4e8864e4b8bc8ba7aac518ac6d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
